### ISSUE TITLE
Has version 0.1.4 been pushed to clojars or central?

### ISSUE THREAD

**Issue by samedhi** [noir-clojure/cljs-template#2]
> > lein plugin install cljs-template 0.1.4
> > [INFO] Unable to find resource 'cljs-template:cljs-template:jar:0.1.4' in repository central (http://repo1.maven.org/maven2)
> > [INFO] Unable to find resource 'cljs-template:cljs-template:jar:0.1.4' in repository clojars (http://clojars.org/repo/)
> > Exception in thread "main" org.apache.maven.artifact.resolver.ArtifactNotFoundException: Unable to download the artifact from any repository

I am using newnew, if that helps to diagnose.

**Comment by myguidingstar-zz** [comment]
Me too. Only 0.1.3 available

**Comment by sjl** [comment]
+1

**Comment by ibdknox** [comment]
fixed
