### ISSUE TITLE
Is there a cljs repl?

### ISSUE THREAD

**Issue by samedhi** [noir-clojure/cljs-template#3]
Pardon if this is a stupid question, but I was wondering whether there is a clojurescript repl in this project? Typing ">> lein repl" does give me a repl, but this is clearly a clojure (not clojurescript) repl. I entered the following a the repl I did have

(do (require '[cljs.repl :as repl]) (require '[cljs.repl.browser :as browser]) (def env (browser/repl-env)) (repl/repl env))

hoping that it might give me a clojurescript repl. It appears to work (with a number of warnings). I then type

(+ 1 2)

I then refresh the browser.

And I am hung, never returns 3. I am guessing that my clojurescript repl is never connecting to the browser. 

Anyway, I know this is not precisely a bug, but if it is possible to get a clojurescript repl, some instructions on how to do so would be useful in the README. If this is a dumb question, apologies again, I am kind of a newb.

**Comment by samedhi** [comment]
With some help, I was able to figure out how to do this. 

In main.cljs,  uncoment the following line (set it to the ip address of the computer hosting if you are connecting from a browser on a different computer):

> >  (repl/connect "http://localhost:9000/repl")

in server.clj, add the following to your namespace definition:

> > (:use [clojure.repl]
> >        [cljs.repl :only (repl)]
> >        [cljs.repl.browser :only (repl-env)])

and define the following method

> > (defn cljs-repl [](repl %28repl-env%29))

Now, open a terminal, 
lein repl
(cljs-repl)
(js/alert "Hello there")

Good to go.

**Comment by ibdknox** [comment]
With noir-cljs 0.2.5, this is now just:

``` clojure
(require '[noir.cljs.repl :as repl])
(repl/browser)
```
